# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            David Blooman
tagline:          'Cloud Infrastructure Made Simple'
description:      'Infrastructure and code by <a href="https://twitter.com/dblooman" target="_blank">@dblooman</a>.'
url:              https://github.com/DaveBlooman
baseurl:          /

author:
  name:           'David Blooman'
  url:            https://github.com/DaveBlooman

paginate:         5

github:
  repo:           https://github.com/DaveBlooman
